site_name: PyMCCE

remote_name: upstream

nav:
    - Overview: index.md
    - For Users:
        - Installation: users/install.md
        - Get Started: users/run.md
        - Make new ftpl files: users/ftpl.md
        - Analyze the results: users/analyze.md
        - Tools Documentation: users/tools.md
    - For Developers:
        - Notes to Developers: developers/notes.md
        - Git Sample Workflow: developers/sharecode_git.md
        - Program Structure: developers/structure.md
        - Pymccelib:
            - Reading Parameters: developers/pymccelib_prmtpl.md
            - PDB IO: developers/pymccelib_pdb.md
            - Structure modification: developers/pymccelib_structure.md
        - Writing Documentation: developers/mkdocs.md

#theme: readthedocs

theme:
    name: material
    logo:
        icon: code
    favicon: assets/favicon.ico
    language: en
    palette:
        primary: teal
        accent: orange
    font:
        text: Roboto
        code: Roboto Mono
    feature:
        tabs: True

markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - markdown_blockdiag:
          format: svg
    - codehilite

    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'